# 错误处理

## introduction

Rust 中没有“异常（exception）”，只有错误：

- 可恢复的错误
- 不可恢复的错误 -- bug



## 处理

### 不可恢复的错误

使用 `panic!("message")` 宏，直接终止程序并且报错 message



**出现错误时使程序产生恐慌的(panic)的快捷方式：**

- `unwrap()`
  -  用于提取 Option 和 Result 类型内部的值
  - 如果出现 None 或者 Err，程序将会调用 panic! 宏并终止
- `expect()`
  - 提取部分和 `unwrap()` 一样，除此之外允许提供一个自定义的 panic 消息

```rust
// 只演示 expect()  --  unwrap() 就是没有 自定义错误提示版本的
use std::fs::File;
fn main() {
    let file_name = String::from("hello.txt");
    File::open(&file_name).expect("打开文件错误");
    println!("如果看到了我就代表没发生错误：xixi");
}

// 在没有文件的情况下，报错如下：
// 打开文件错误: Os { code: 2, kind: NotFound, message: "系统找不到指定的文件。" }
```









### 可恢复的错误

使用 `Result` 枚举处理可恢复的错误

```rust
// T, E 为泛型类型
enum Result<T, E>{
    Ok(T),
    Err(E),
}
```





### 传播错误 (Propagating Errors)

> **将错误返回，由调用改函数的代码来决定如何处理错误**

使用 `?` 运算符而避免使用多个 `match` 语句可以简化代码(避免大量的 `match` 或 `if let` 语句)，增强可读性！



**在哪里可以使用 `?` 运算符？**

`?` 可以使用在返回类型是 `Option`, `Result` 等实现了 FromResidual trait 的类型的函数里

1. 使用 `?` 运算符作用于 `Result` 枚举：
   - 如果操作成功，它会解包 `Ok` 并继续执行
   - 如果操作失败，它会立即返回（return, 并且是作为函数的返回值，不会解包） `Err`，并将错误传播给调用者使用
2. 使用 `?` 运算符作用于 `Option` 枚举：
   - 如果操作成功，会解包 `Some` 并继续执行
   - 如果操作失败，会立刻返回 `None` 作为返回值



**错误类型的转换**

`from` 函数： 在 `?` 运算符接收到 `Err` 的结果之后，会将其转换为函数需要的返回值类型

- 把值从一个类型转化为另一个类型 
- 定义在 std 的 From trait 上

-- >  **例子**： 如果函数需要返回 `Result <T, E>`, 而 `?` 接收到的错误类型为 `E2`, 则会调用 `from `函数把` E2` 转换成 `E`









## talk is cheap, show me the code



- 先写一个创建并且打开文件的函数：

```rust
use std::fs::File;
use std::io::ErrorKind;
fn creat_and_open_file_with_panic(file_path: &str) -> File{
    match File::open(file_path) {
        Ok(file) => file,
        Err(err) =>  match err.kind() {
            ErrorKind::NotFound => match File::create(file_path) {
                Ok(file) => file,
                Err(err) => panic!("creating file failed: {err:?}"),
            },
            other_err => panic!("opening file failed: {other_err:?}"),
        }
    }
}
```



**这个 match 表达式会返回文件的句柄，如果过程中出现错误，就会终止整个程序**



- 但是我们不希望出现一点错误就终止程序，而是将错误传递出去，交给调用函数的代码去判断！
- 下面使用一个读取文件内容的函数演示

```rust
use std::fs::File;
use std::io::ErrorKind;
use std::io;
fn read_file_content(file_path: &str) -> Result<String, io::Error>{   
    let mut file = match File::open(file_path) {
        Ok(file) => file,
        Err(err) => return Err(err),
    };
    let mut content = String::new();
    match file.read_to_string(&mut content) {
        Ok(_) => Ok(content),
        Err(err) => Err(err),
    }
}
```



返回 Result 类型的枚举保证了返回类型的一致性！ 其中的 `String` 和 `io::Error` 可以 **更换成自己的数据类型**（某些自定义类等），来返回想要的信息



- 可是写这些 `match` 表达式还是太复杂了，有没有更加简洁的写法？
- 有的，兄弟，有的。像（比）这样（更）简洁的写法还有九种（大雾）  —— 至少我们可以使用 `?` 运算符来简化代码

```rust
fn read_file_content(file_path: &str) -> Result<String, io::Error>{   
    let mut file = File::open(file_path)?;
    let mut content = String::new();
    file.read_to_string(&mut content)?;
    Ok(content)
}
```



- 还可以进一步链式调用 -- **优雅！！**：

```rust
fn read_file_content(file_path: &str) -> Result<String, io::Error>{   
    let mut content = String::new();
    File::open(file_path)?.read_to_string(&mut content)?;
    Ok(content)
}
```



- 当然，对于这个功能，标准库已经实现了，所以使用时就不用套这个壳子了：

```rust
use std::fs;
fn read_file_content(file_path: &str) -> Result<String, io::Error>{   
    fs::read_to_string(file_path)    
}
```



- 但是项目代码中我们经常需要返回自己的错误类型，如何让`?` 表达式也能用在我们自己的错误类型上？
- 使用 **from trait**！

```rust
enum MyError{
    Io(io::Error),
    ParseInt(num::ParseIntError),
    Other(String),
}  

impl From<io::Error> for MyError{
    fn from(value: io::Error) -> Self {
        MyError::Io(value)
    }
}
impl From<num::ParseIntError> for MyError {
    fn from(value: num::ParseIntError) -> Self {
        MyError::ParseInt(value)
    }
}
fn test1() -> Result<String, MyError>{
    let content = fs::read_to_string("hello.txt")?;
    let mut number: i32 = "55".parse()?;
    Ok(content)
}
```



